title: Ulbrich Frauendorf

logo: 1.png # Use a relative path to logo image

description: Senior Software Engineer - Building innovative solutions with precision and passion. # Fix hyphenation

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal

plugins: jekyll-seo-tag # Add SEO plugin
email: ulbrich.frauendorf@gmail.com # Allow visitors to contact you
