title: Ulbrich Frauendorf

logo: 1.png # Use a relative path to logo image

description: Senior Software Engineer - Building innovative solutions with precision and passion. # Fix hyphenation

show_downloads: true # Fix spelling

remote_theme: pages-themes/hacker@v0.2.0

plugins: 
  - jekyll-seo-tag
  - jekyll-remote-theme
  
email: ulbrich.frauendorf@gmail.com # Allow visitors to contact you
